baseURL = 'http://knml.edu.pl/'
languageCode = 'pl-PL'
title = 'Koło Naukowe Machine Learning Politechniki Rzeszowskiej'
theme = 'hugo-profile'

Paginate = 3
enableRobotsTXT = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "RSS" ]

[markup.goldmark.renderer]
unsafe = true

[[Menus.main]]
identifier = "blog"
name = "Blog"
title = "Blog posts"
url = "/blogs"
weight = 1

[[Menus.main]]
identifier = "gallery"
name = "Gallery"
title = "Blog posts"
url = "/gallery"
weight = 2

[params]
title = "Koło Naukowe Machine Learning Politechniki Rzeszowskiej"
description = "Strona główna Koła Naukowego Machine Learning"
favicon = "/fav.png"
useBootstrapCDN = false
animate = true

  [params.font]
  fontSize = "1rem"
  fontWeight = 400
  lineHeight = 1.5
  textAlign = "left"

  [params.navbar]
  align = "ms-auto"
  brandName = "KNML"
  disableSearch = true

    [params.navbar.menus]
    disableAbout = true
    disableExperience = true
    disableEducation = true
    disableProjects = true
    disableAchievements = true
    disableContact = true

  [params.hero]
  enable = true
  intro = "Cześć, jesteś na stronie głównej"
  title = "Koła naukowego Machine Learning"
  subtitle = "Politechniki Rzeszowskiej"
  content = "Wykorzystujemy uczenie maszynowe do rozwiązywania niecodziennych problemów."
  image = "/images/hero.svg"

    [params.hero.bottomImage]
    enable = true

    [params.hero.button]
    enable = true
    name = "Linktree"
    url = "https://linktr.ee/knml.prz"
    download = false
    newPage = true

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/knmlprz"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-facebook"
url = "https://www.facebook.com/knmlprz"



  [params.about]
  enable = false
  title = "O nas"
  image = "/images/me.png"
  content = """
Jesteśmy kołem zrzeszającym osoby chcące poszerzyć swoją wiedzę w zakresie uczenia maszynowego i sztucznej inteligencji.
"""

    [params.about.skills]
    enable = false
    title = "Here are a few technologies I've been working with recently:"
    items = [ "HTML", "CSS", "JavaScript", "React", "Node", "Express" ]

  [params.experience]
  enable = false

    [[params.experience.items]]
    job = "Senior Software Developer"
    company = "Facebook"
    companyUrl = "https://example.com"
    date = "Jan 2022 - present"
    content = "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

      [params.experience.items.featuredLink]
      enable = true
      name = "View the project"
      url = "https://example.com"

    [[params.experience.items]]
    job = "Software Developer"
    company = "Amazon"
    companyUrl = "https://example.com"
    date = "Sep 2020 - Dec 2021"
    content = """
I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

- Lead backend developer for a product.
- Created a frontend design for a product.
"""

      [params.experience.items.featuredLink]
      enable = true
      url = "https://example.com"

      [params.experience.items.info]
      enable = true
      content = "I worked as a software developer for more than one year in Amazon."

    [[params.experience.items]]
    job = "Junior Software Developer"
    company = "Apple"
    companyUrl = "https://example.com"
    date = "Jan 2020 - Aug 2020"
    content = """
I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

- Lead backend developer for a product.
- Created a frontend design for a product.
"""

      [params.experience.items.info]
      enable = false

      [params.experience.items.featuredLink]
      enable = true
      url = "https://example.com"

    [[params.experience.items]]
    job = "UI/UX Designer"
    company = "Netflix"
    companyUrl = "https://example.com"
    date = "June 2017 - Nov 2019"
    content = """
I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

- Lead backend developer for a product.
- Created a frontend design for a product.
"""

      [params.experience.items.featuredLink]
      enable = true
      url = "https://example.com"

    [[params.experience.items]]
    job = "Product Designer"
    company = "Google"
    companyUrl = "https://example.com"
    date = "Feb 2016 - Mar 2017"
    content = "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  [params.education]
  enable = false
  index = false

    [[params.education.items]]
    title = "Master of Business Administration"
    date = "2013 - 2015"
    GPA = "3.8 out of 5.0"
    content = """
Extracurricular Activities
  - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
  - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique."""

      [params.education.items.school]
      name = "University of California, Berkeley"
      url = "https://example.org"

    [[params.education.items]]
    title = "Bachelor of Science in Computer Science"
    date = "2009 - 2013"
    GPA = "3.9 out of 5.0"
    content = """
I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
- [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
- Face mask detection using a single convolutional neural network.

Extracurricular Activities
  - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
  - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique."""

      [params.education.items.school]
      name = "Massachusetts Institute of Technology"
      url = "https://example.org"

      [params.education.items.featuredLink]
      enable = true
      name = "My academic record"
      url = "https://example.com"

    [[params.education.items]]
    title = "High School"
    GPA = "4.2 out of 5.0"

      [params.education.items.school]
      name = "Thomas Jefferson High School for Science and Technology."
      url = "https://example.org"

      [params.education.items.featuredLink]
      enable = true
      url = "https://example.com"

  [params.achievements]
  enable = false

    [[params.achievements.items]]
    title = "Google kickstart runner"
    content = "I solved all problems with optimal solution."
    url = "https://example.com"

    [[params.achievements.items]]
    title = "Facebook Hackathon Winner"
    content = "Developed a product using Artificial Intelligence."

    [[params.achievements.items]]
    title = "Koło Naukowe Machine Learning Politechniki Rzeszowskiej"
    content = "Developed a theme and getting 1K+ downloads per month."
    url = "https://github.com/gurusabarish/hugo-profile"

    [[params.achievements.items]]
    title = "Microsoft Imagine Runner"
    content = "We are developed a product which can help others."

    [[params.achievements.items]]
    title = "Google Summer of Code"
    content = "Contributed to a open source project."
    url = "https://example.com"

  [params.projects]
  title = "Projekty"
  enable = false

    [[params.projects.items]]
    title = "LoveSpeachHelper"
    content = "Wykrywanie negatywnych emocji w sieci; drugie miejsce na BITEHack 2022 w kategorii AI"
    image = "/images/projects/profile.png"
    badges = [ "Python", "pytorch", "Tensorflow" ]

      [params.projects.items.featured]
      name = "Repozytorium"
      link = "https://github.com/knmlprz/BITEHack"


    [[params.projects.items]]
    title = "Image Converter"
    content = "A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django."
    image = "/images/projects/converter.jpg"
    badges = [ "Django", "Bootstrap" ]

      [params.projects.items.featured]
      name = "Demo"
      link = "https://django-converter.herokuapp.com"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/converter"

    [[params.projects.items]]
    title = "Koło Naukowe Machine Learning Politechniki Rzeszowskiej V2"
    content = "A clean and simple Hugo template for personal portfolio and blog."
    image = "/images/projects/profile2.jpg"
    badges = [ "Hugo", "Bootstrap", "Javascript" ]

      [params.projects.items.featured]
      name = "Demo V2"
      link = "https://hugo-profile-2.netlify.app"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/HugoProfileV2"

  [params.contact]
  enable = false
  content = "My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!"
  email = "gurusabarisha@gmail.com"
  btnName = "Mail me"

[params.footer.recentPosts]
path = "blogs"
count = 3
title = "Recent Posts"
enable = false
disableFeaturedImage = false

[params.footer.socialNetworks]
github = "https://github.com/knmlprz"
linkedin = "https://www.linkedin.com/company/knmlprz/"
instagram = "https://www.instagram.com/knml.prz/"
facebook = "https://www.facebook.com/knmlprz"

  [params.listPages]
  disableFeaturedImage = false

[params.singlePages.readTime]
enable = true
content = "min read"

[params.singlePages.scrollprogress]
enable = true

  [params.terms]
  read = "Read"
  toc = "Table Of Contents"
  copyright = "All rights reserved"
  pageNotFound = "Page not found"
  emailText = "Check out this site"

  [params.datesFormat]
  article = "Jan 2, 2006"
  articleList = "Jan 2, 2006"
  articleRecent = "Jan 2, 2006"